kernel:
  id: kernel-1

spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/agentdb
    username: agent
    password: agentpass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  application:
    name: kernel-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    should-unregister-on-shutdown: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30


server:
  port: 8080
